baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Holy Bone! Productions'
theme = 'XMin'
[menus]
    [[menus.main]]
        name = 'Home'
        pageRef = '/'
[markup.goldmark.renderer]
unsafe= true
