baseURL = 'https://holybone.zone/'
languageCode = 'en-us'
title = 'Holy Bone! Productions'
theme = 'XMin'
[menus]
    [[menus.main]]
        name = 'Home'
        pageRef = '/'
        weight = 10
    [[menus.main]]
        name = 'Projects'
        pageRef = '/projects'
        weight = 20
    [[menus.main]]
        name = 'Contact'
        pageRef = '/contact'
        weight = 30

[markup.goldmark.renderer]
unsafe= true
